### ISSUE TITLE
nointerrupts problem

### ISSUE THREAD

**Issue by Adrianotiger** [adafruit/Adafruit_NeoPixel#109]
Hi,
I know that it is important that the Arduino doesn't get interrupts when setting the LED Strip.
But sometimes it is also important (more important) to get an interrupt instead of setting the LEDs.

Example an IR-Remote.

So my question:
Is it possible to add a function (disableNoInterrupts() for example) to allow interrupts? I know, the LED strip will probably show other colors or will not update for 1 show()-command. But the IR-remote command will be accepted without use another Arduino. Maybe the library can detect if an interrupt is arrived and so it will not update the led strip until the next show() is called.

**Comment by ladyada** [comment]
for that you should just edit the library and remove the cli() calls
