### ISSUE TITLE
Using Adafruit_NeoPixel .cpp and header file on Raspberry Pi

### ISSUE THREAD

**Issue by bomanimc** [adafruit/Adafruit_NeoPixel#110]
Hi,

Thanks for the work on this! I am working on a project in C on raspberry Pi and I wonder if anyone has ever tested using the .h and .cpp files in this project on Raspberry Pi. To write a script, I could use the wiringPi library Does this sound feasible, and if so do you have any suggestions on how it might be done?

**Comment by ladyada** [comment]
totoooootally wont work! plz use the existing neopixel raspi code :)
