### ISSUE TITLE
Adafruit_NeoPixel.cpp:935:28: error: duplicate asm operand name

### ISSUE THREAD

**Issue by robertvandervoort** [adafruit/Adafruit_NeoPixel#138]
It seems some recent updates to the NeoPixel library has broken its ability to compile on the trinket pro 3v

I have verified this by going through the cpp file's history on github and grabbing an older commit from 2016 and it compiles fine. It looks like the duplicate the error talks about is in one of the newer refresh rate code blocks...

..\Arduino\libraries\Adafruit_NeoPixel\Adafruit_NeoPixel.cpp: In member function 'void Adafruit_NeoPixel::show()':

..\Arduino\libraries\Adafruit_NeoPixel\Adafruit_NeoPixel.cpp:935:28: error: duplicate asm operand name 'lo'

         [ptr]    "e" (ptr));

                            ^

exit status 1
Error compiling for board Pro Trinket 3V/12MHz (USB).

**Comment by ladyada** [comment]
? sorry cannot replicate! please try IDE 1.8.4+ and latest BSP - reopen if it happens again? :)
