### ISSUE TITLE
STM32L4 support?

### ISSUE THREAD

**Issue by Jorgen-VikingGod** [adafruit/Adafruit_NeoPixel#140]
- Arduino board: **NUCLEO-L432** (https://github.com/GrumpyOldPizza/arduino-STM32L4)
- Arduino IDE version (found in Arduino -> About Arduino menu):  **1.8.0**
- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): just try the example **simple.ino**

**Comment by ladyada** [comment]
does not exist at this time, if you want to submit a PR we'd take a look! :)
