### ISSUE TITLE
Adding support for the Arduino Tau from Rabid Prototypes

### ISSUE THREAD

**Issue by jnavarro1178** [adafruit/Adafruit_NeoPixel#143]
Please add 
    defined (\_\_SAMD21E17A\_\_) 
to the #ifdef check in line 1490 of Adafruit_NeoPixel.cpp

This adds support for the Arduino Tau from Rabid Prototypes and everything works fine after this change.

Thank you.

**Comment by ladyada** [comment]
hiya can you fork, test, and submit a pull req? (we have no way of testing with the hardware)

**Comment by jnavarro1178** [comment]
Done. Thank you.

**Comment by ladyada** [comment]
this is still open but we pulled the PR so its all good now - closing! plz reopen if not workin'
