### ISSUE TITLE
Add support for through-hole WS2812 LEDs

### ISSUE THREAD

**Issue by andrey-gvrd** [adafruit/Adafruit_NeoPixel#145]
Product page — https://www.adafruit.com/product/1938

Even though you'd expect them to work out-of-the-box since they're supposedly WS2812s, adafruit description mentions this: "Note that these are "RGB" instead of "GRB" format used in the 5050-sized LEDs you are so used to." so they're not.

In practice the problem with them is sort of hard to explain — LEDs light up when they shouldn't, with seemingly random colors.

**Comment by PaintYourDragon** [comment]
Unlike the strips and shapes, through-hole WS2812's don't include decoupling capacitors. A 0.1 uF cap across the + and - legs of each LED (or in a pinch, sometimes every second one will suffice) should clear this up.
