### ISSUE TITLE
getPixelColor() doesn't return exact values and is missing the white value

### ISSUE THREAD

**Issue by WieJaay** [adafruit/Adafruit_NeoPixel#151]
The NeoPixel Überguide says "You can query the color of a previously-set pixel using getPixelColor()." and "This returns a 32-bit merged color value.". I am getting a 24-bit value (it doesn't include white) and the red, green and blue values are slightly dimmed (e.g. 250 instead of 255).

**Comment by PaintYourDragon** [comment]
This can happen if using the setBrightness() function at anything less than 255. Brightness scaling is a lossy operation at the time of setPixelColor() -- there's no getting the original value back, only a 'de-scaled' approximation. If consistent values are required for an application, leave the brightness at the max setting and instead change the 'set' color values in the code.

Not sure what's up with white. Just checked the code and it does appear to be handling that. Might again be a destructive scaling operation of using less than full brightness and a not-particularly-bright white value (will get rounded to 0).
