### ISSUE TITLE
setBrighness(0) somehow destroys the program

### ISSUE THREAD

**Issue by sakulstra** [adafruit/Adafruit_NeoPixel#167]
It seems like setBrightness(0) somehow also removes the colors in contrast to setBrightness(anyOtherValue).

This is somehow related to #55 I guess, but not exactly the same as I don't use setBrighness in loops or similar. It's just rarely called when a specific serial message comes in.

- Arduino board: Arduino Nano

- Arduino IDE version (found in Arduino -> About Arduino menu):  1.8.5

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): 

It's kind of hard to copy over all the code as my current sketch is based on multiple arduinos communicating to each other over ble. So here is only the relevant gist.

```ino
#include <SoftwareSerial.h>
#include <Adafruit_NeoPixel.h>
#ifdef __AVR__
  #include <avr/power.h>
#endif

#define PIXEL_PIN 8
#define PIXEL_NUM 30

Adafruit_NeoPixel strip = Adafruit_NeoPixel(PIXEL_NUM, PIXEL_PIN, NEO_GRB + NEO_KHZ800);

// the setup routine runs once when you press reset:
void setup() {
  // initialize serial communication at 9600 bits per second:
  Serial.begin(9600);

  strip.begin();
  strip.show(); // Initialize all pixels to 'off'
  strip.setBrightness(0); // for any other value != 0 the code works as expected
  colorWipe(strip.Color(255, 0, 0));
}

// the loop routine runs over and over again forever:
void loop() {
  delay(2000);        // delay in between reads for stability
  strip.setBrightness(150);
  // colorWipe(strip.Color(255, 0, 0)); -> when I manually reset the colors it works as well
  strip.show();
}

// Fill the dots one after the other with a color
void colorWipe(uint32_t c) {
  for(uint16_t i=0; i<strip.numPixels(); i++) {
    strip.setPixelColor(i, c);
    strip.show();
  }
}
```

**Comment by ladyada** [comment]
not a bug, set brightness is a permanent-one-way function. set it once at the beginning of your program
