### ISSUE TITLE
Proposal: show() function simplification

### ISSUE THREAD

**Issue by hattesen** [adafruit/Adafruit_NeoPixel#169]
@ladyada, this relates to your first "wishlist" item in the `README.MD`...

> For the show() function (with all the delicate pixel timing stuff), break out each architecture into separate source files rather than the current unmaintainable tangle of #ifdef statements!

Would it not be a more tidy (and flexible) solution, to have identical cycle-counting code for ALL processors, that uses countdown loops to spend a predetermined number of cycles (microseconds) - over and above the number of cycles that the code outside the countdown loop requires. That way, each processor only needs to define a single, constant integer, that is then used in the countdown loop, possibly with a constant arithmetic expression to account for long and short bit slices.

I know that a lot of time and effort has gone into cycle counting the current code for the different processors, and that a major refactoring like this carries a level of risk, but I believe the outcome would justify it. It would mean, that adding another processor to the list would require no more than defining another constant. The constant could either be established formally, by cycle counting the code, or by experimentation (using binary search) with an oscilloscope monitoring the bit timing.

What about creating a GIT branch for experimenting with implementing a simplified, yet flexible, way of controlling the timing critical, cycle counting, part of the NeoPixel library? I would be happy to work on it, and perform testing (oscilloscope timing), but my general assembler skills are rusty (1980's CPUs).

**Comment by ladyada** [comment]
thanks! as per the TODO we *would* be interested in a PR that splits it up into different files but *not* one that replaces the cycle-counting code. 8/16-mhz chips simply cannot use loops they are too slow, nops work great. and anything faster has enough flash that a few-dozen nops are of no consequence.
