### ISSUE TITLE
Micro:Bit DF Robot Maqueen Pin Issue 

### ISSUE THREAD

**Issue by kd8bxp** [adafruit/Adafruit_NeoPixel#174]
I'm having an issue getting neopixels to work on Pin 15 (P15). I have a DF Robot Maqueen Robot
https://www.dfrobot.com/wiki/index.php/Micro:Maqueen_Robot_Car(V2.0)_SKU:_ROB0148
which is using P15 for the 4 neopixels that are on board. The provided makecode works, so I know the neopixels work. I also verified that I can use neopixels with the example provided here https://learn.adafruit.com/micro-bit-lesson-3-neopixels-with-micro-bit/software
with the neopixels attached to Pin 2. 
I feel like I am missing something somewhere, but I'm unsure what that might be. Any ideas?

- Arduino board: Micro:Bit with DF Robot Maqueen v2 robot

- Arduino IDE version (found in Arduino -> About Arduino menu):  1.8.5

Library Version 1.1.6  (also tried with 1.1.5)

**Comment by kd8bxp** [comment]
After doing a lot of searching, and reading (but not finding an answer). 
I think the problem maybe that BLE is turned on and/or needs to be disabled.  Does anyone know how to turn of BLE using the Arduino IDE? I really could use some help with one.  Thanks.

**Comment by ladyada** [comment]
hiya - this is a good question to ask DF robot tech support! they can submit a PR or update their instructions if necessary.
