### ISSUE TITLE
 I need help. Why fall off WI-FI in AP mode with WS2812FX / NeoPixel?

### ISSUE THREAD

**Issue by Legantmar** [adafruit/Adafruit_NeoPixel#176]
There is a direct dependence on the number of LEDs in the WS2812FX() class and the stability of WI-Fi in the access point mode. (in client mode, stability is much higher.). 
Why ??  :( 
My simplified code in attachment 
https://yadi.sk/d/Mg9UCTbJfZgvng

Note: the start page address is 192.168.4.1
1) no LED strip is needed to check the sketch
2) before uploading the sketch, first upload the data (from the data folder)
3) I am using an older ws2812fx slightly modified (attached)
4) to check free memory-192.168.4.1/mem

Problem - Wi-Fi suddenly falls off in access point mode:
1) when loading web pages
2) when you turn on the buttons on the start page
3) the problem is stronger/faster manifested, the higher the LED_COUNT value for the WS2812FX class()
LED_COUNT = 600 - web pages can not be loaded at all. Wi-Fi falls off right away
LED_COUNT = 100 - it may seem that everything is fine, but after a while (the number of requests, connections), Wi-Fi also falls off.
You do not have the required permissions to view the files attached to this post.

**Comment by ladyada** [comment]
probably because neopixels turn off interrupts. esp8266 doesn't like that. you may want to try other LEDs.  we don't do design or tech support in issues - please post on the forum of where you purchased your wifi board.

**Comment by nylen** [comment]
> probably because neopixels turn off interrupts. esp8266 doesn't like that.

This was a pretty hard bit of info to find!  Can it be documented better here?
