### ISSUE TITLE
Pixels do not light up if data pin is not set to OUTPUT

### ISSUE THREAD

**Issue by realrolfje** [adafruit/Adafruit_NeoPixel#189]
Arduino board:  Arduino MEGA2560
Arduino IDE version (found in Arduino -> About Arduino menu):  PlatformIO

**Steps to reproduce:**
When using the neopixel library like this:

```C
  Adafruit_NeoPixel strip = Adafruit_NeoPixel(NUM_LEDS, NEOPIXEL_PIN, NEO_GRBW + NEO_KHZ800);
```
Writing a color to a pixel and calling show() seems to do nothing. After following all tips about wiring, capacitors and checking the code, nothing seemed to help. It turns out there is one line of code that needed to be added:

```C
pinMode(NEOPIXEL_PIN, OUTPUT);
```

It took me 2 days to figure this out, and I expect this can be confusing to others too, since the constructor indicates which pin to use to write data to the pixels.

**Comment by ladyada** [comment]
you need to call begin()

https://github.com/adafruit/Adafruit_NeoPixel/blob/master/Adafruit_NeoPixel.cpp#L74
