### ISSUE TITLE
Issues with long strings past 255 pixels 

### ISSUE THREAD

**Issue by STiFTW** [adafruit/Adafruit_NeoPixel#21]
I am still going through the code but I am seeing some odd behavior when going past 255 neopixles (not an issue with the power supply).  Currently running on a Uno which has no memory problems up to 550 pixels with all the code I have thrown at it so far. 

When I try to go past 255 pixles (256 and higher) the strip animation switches direction (ends) and does some strange things such as leaving LEDs on or having gaps in the strip. 

I figure there must be an unsigned 8-bit integer that I am overrunning in the code somewhere since 255 is the magic number I am having trouble with.

**Comment by ophirr** [comment]
Looks like it was just "uint8_t neoPixelToChange = 0;  //track which neoPixel to change".

Changing to "uint16_t neoPixelToChange = 0; //track which neoPixel to change" fixed the problem. :)
