### ISSUE TITLE
Warning: unused Parameter 800 kHz

### ISSUE THREAD

**Issue by hasenradball** [adafruit/Adafruit_NeoPixel#220]
- Arduino board:  ESP8266-01, ESP8266, Demos mini D1

- Arduino IDE version (found in Arduino -> About Arduino menu):
  - IDE ver: 1.8.9;
  - ESP core 2.6.3 

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): **LIST REPRO STEPS BELOW**

During compile the following issue occur:

```
/Users/frank/Documents/Arduino/libraries/Adafruit_NeoPixel/esp8266.c: In function 'espShow':
/Users/frank/Documents/Arduino/libraries/Adafruit_NeoPixel/esp8266.c:21:59: warning: unused parameter 'is800KHz' [-Wunused-parameter]
  uint8_t pin, uint8_t *pixels, uint32_t numBytes, boolean is800KHz) {
                                                           ^
```
Questions:
- What ist the root cause of this issue?
- What ist the difference between 800kHz and 400 kHz?

**Comment by ladyada** [comment]
we dont support 400 khz on esp, this is not a bug, you can ignore the wanring
