### ISSUE TITLE
How to sync using custom for loop?

### ISSUE THREAD

**Issue by Berkays** [adafruit/Adafruit_NeoPixel#223]
I want to use 1 byte per led in the strip because of the sram limit of CPU. Is it possible to allocated 1 byte per led at the expense of having only white color? How would i sync this byte array with the strip?
I think it should be possible to send same value 3 times for rgb values from the single byte per led array.

**Comment by ladyada** [comment]
nope - not possible with the library, it would require a complete rewrite of the neopixel handling! :)

**Comment by Berkays** [comment]
Why would it need a complete rewrite? I only have to send the array values 3 times doesnt it?

**Comment by ladyada** [comment]
the code is completely unstructured for that kinda usage - you could fork and modify it for your own needs :)

**Comment by Berkays** [comment]
I would try modifying it if assembly was not involved :)
