### ISSUE TITLE
New Feature Request - Show to allow parms Show(StartingAt, EndingAt)

### ISSUE THREAD

**Issue by BobVal** [adafruit/Adafruit_NeoPixel#225]
Would be nice if Show could take parameters Starting At to Ending At

I have a long string and have routines that work on different sections of it at different times.
Calling show updates the whole string causing a lot of unnecessary flicker

I am not sure if it is possible to update the string in sections but would be nice.

Would surely appreciate it

BobVal

**Comment by ladyada** [comment]
hi the way these pixels work is you must write the entire strip at once
