### ISSUE TITLE
how can i use Adafruit_NeoPixel on Python 2.7?

### ISSUE THREAD

**Issue by i1212-blip** [adafruit/Adafruit_NeoPixel#239]
I'm running many scripts on python 2.7. So I want to run Adafruit_NeoPixel on python 2.7. How can i do it ?

**Comment by FoamyGuy** [comment]
Sorry Python 2 is officially no longer supported. This was a decision by the Python Software Foundation. You can learn more about it here: https://www.python.org/doc/sunset-python-2/ 

You will need to upgrade to a version python 3 if you want to use a version that is supported.
