### ISSUE TITLE
Suggestion : Merge changes from a fork which supports Kendryte K210 processor (Maix Sipeed boards)

### ISSUE THREAD

**Issue by dimitre** [adafruit/Adafruit_NeoPixel#242]
This fork https://github.com/baorepo/Adafruit_NeoPixel has support to K210 processor, it would be great to have this support here too.

**Comment by ladyada** [comment]
great, please submit a PR, we don't have a K210 to test with

**Comment by ladyada** [comment]
we merged support here
https://github.com/adafruit/Adafruit_NeoPixel/pull/243
