### ISSUE TITLE
C code or pseudo code from PORTD in AdaFruit-Neopixel.cpp

### ISSUE THREAD

**Issue by Petros626** [adafruit/Adafruit_NeoPixel#258]
Hi guys,

ladyada has already listed the assembler code with its cycles in the listing of PORTD. I would like to know if the following lines still belong to the assembly code or what they are for. Preferably in C or pseudo code,so I can understand what is happening here. It would also be helpful to know how many clocks are used per step in this section (only if it is assembler).

code section:

line 365-372: 

 : [byte]  "+r" (b),
        [n1]    "+r" (n1),
        [n2]    "+r" (n2),
        [count] "+w" (i)
      : [port]   "I" (_SFR_IO_ADDR(PORTD)),
        [ptr]    "e" (ptr),
        [hi]     "r" (hi),
        [lo]     "r" (lo));

Kind regards

Petros

**Comment by ladyada** [comment]
marked as off topic, we don't do code walkthrus on github
please do not open again, you can post on a forum for assembler folks to get a walkthru assistance
