### ISSUE TITLE
blink example for QTPy onboard NeoPixel

### ISSUE THREAD

**Issue by drewfish** [adafruit/Adafruit_NeoPixel#262]
In the [learning guide for the QTPy](https://learn.adafruit.com/adafruit-qt-py) I couldn't find a mention of how to blink the onboard NeoPixel. It does say that the QTPy does not have an onboard pin 13 LED, but it makes no mention of how to use the onboard NeoPixel.

So, it might be nice to have a standard "blink" example sketch which blinks the onboard NeoPixel.

I did come up with something, but it isn't as polished (with useful comments) as examples tend to be:

```cpp
#include <Adafruit_NeoPixel.h>
Adafruit_NeoPixel pixels(1, PIN_NEOPIXEL);

void setup() {
    pixels.begin();
}

void loop() {
    pixels.setPixelColor(0, pixels.Color(255, 0, 0));
    pixels.show();
    delay(1000);
    pixels.clear();
    pixels.show();
    delay(1000);
}
```

**Comment by ladyada** [comment]
good idea, added here
https://learn.adafruit.com/adafruit-qt-py/neopixel-blink
