### ISSUE TITLE
SAME5x support?

### ISSUE THREAD

**Issue by tohox** [adafruit/Adafruit_NeoPixel#265]
Hi,

I'm trying to get this library running on a [ClearCore industrial Arduino built by Teknic](https://www.teknic.com/files/downloads/clearcore_user_manual.pdf) which utilizes the SAME53N19A chip.

The same RGBWstrandtest.ino example sketch which runs OK on a Trinket compiles and runs without complaining on the ClearCore but I get no output on the specified LED pin with the latter. I noticed a warning somewhere about the library not working with portA on some chipsets so I tried using a pin on portC but no luck there either.

Any insight would be much appreciated!

Thanks,

**Comment by ladyada** [comment]
hiya please ask clearcore for help & support - we dont own anything with SAME53 on it!
