### ISSUE TITLE
pixels.begin() is freezing my board

### ISSUE THREAD

**Issue by quiquelhappy** [adafruit/Adafruit_NeoPixel#293]
```
#include <Adafruit_NeoPixel.h>
#ifdef __AVR__
  #include <avr/power.h>
#endif
#define PIN        6
#define NUMPIXELS 11

Adafruit_NeoPixel pixels(NUMPIXELS, PIN, NEO_GRB + NEO_KHZ800);

void setup() {
  Serial.begin(9600);
  pixels.begin();
}

void loop() {
    pixels.setPixelColor(0, pixels.Color(0, 150, 0));
    pixels.show();
}
```

board: h[ttps://www.amazon.es/gp/product/B074Q2WM1Y/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1](https://www.amazon.es/gp/product/B074Q2WM1Y/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1)

**Comment by ottobonn** [comment]
Could you clarify what you mean by "freezing"? Does other code not run after you call `begin`? How did you verify that it is stuck there?
