### ISSUE TITLE
Code not executing at led count 395 and above on arduino uno

### ISSUE THREAD

**Issue by drakejest** [adafruit/Adafruit_NeoPixel#296]
Hello I have a problem where the code is not executing at high led counts to be specific i was able to track down the number to 395 on my arduino uno, 394 still works but 395 wont.

I was able to replicate this problem on the neopixel RGBWstrandtest example where the only thing modified is the led count.

I am using the following for components:

Arduino Uno R3
Arduino IDE 1.8.16
Neopixel RGBWstrandtest example (unmodified expemt for the led count)
SK6812 RGBW LED STRIP

**Comment by ladyada** [comment]
you are running out of memory
