### ISSUE TITLE
ESP8266 compilation error

### ISSUE THREAD

**Issue by Voguecocktail** [adafruit/Adafruit_NeoPixel#314]
Hi,
- Arduino board:  WEMOS D1
- Arduino IDE version (found in Arduino -> About Arduino menu):  Web Editor
- List the steps to reproduce the problem below: RGBWstrandtest.ino compile and follow error:

```
Using library adafruit_neopixel_1_10_3 at version 1.10.3 in folder: /home/builder/opt/libraries/adafruit_neopixel_1_10_3
/home/builder/opt/libraries/latest/adafruit_neopixel_1_10_3/esp8266.c:20:11: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'void'
IRAM_ATTR void espShow(
^
Error during build: exit status 1

```
Best regards

**Comment by ladyada** [comment]
please try latest desktop IDE, with latest ESP8266 board support package and libraries, we can't reproduce the error :)
