### ISSUE TITLE
Not sure how to light individual LEDS

### ISSUE THREAD

**Issue by bonellolola** [adafruit/Adafruit_NeoPixel#318]
Hi, I am using a 60 LED neopixel strip. I have managed to light all of the strip, using pixels.fill, but would like to switch the first 20 LEDS a green colour, LED 21-40 to yellow and 41-60 to red. Is there a command I can use for this please?

Thank you so much!!!

**Comment by ladyada** [comment]
hi please post to the arduino or other online coding forums for help on using arduino
