### ISSUE TITLE
.show() not working on RPi Pico

### ISSUE THREAD

**Issue by Xarbenence** [adafruit/Adafruit_NeoPixel#366]
Hello,

I am trying to use this library on the Raspberry Pi Pico, built within the Arduino environment within Platform.IO

Does this library not support the pico board?

**Comment by PaintYourDragon** [comment]
Tested, works on Pico, Arduino IDE w/Earle Philhower RP2040 core. Unsure about Platform.IO.

**Comment by euphemism** [comment]
Also attempting to light up some NeoPixels using an RP2040, the Earle Philhower core, and PlatformIO. Seems to hang when `show()` is called.

**Comment by PaintYourDragon** [comment]
I wonder if Platform.IO does something differently with setting up or assigning PIO. Might’ve encountered this before, it sounds almost familiar.

In Adafruit_NeoPixel.h, near the bottom, look for:
`  PIO pio = pio0;`
Change pio0 to pio1 and see if any difference. If so, maybe we put an #ifdef around it for Platform.IO.

**Comment by taunoe** [comment]
I got mine to work with PlatformIO
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
and PIO pio = pio0;

**Comment by ladyada** [comment]
closing due to no response & not reproducable
