### ISSUE TITLE
Raspberry Pi 5 support

### ISSUE THREAD

**Issue by ubopod** [adafruit/Adafruit_NeoPixel#372]
Neopixel is not working on Raspberry Pi 5. There is an open issue for this in core library but I thought it will be beneficial to bring this to light here as well. 

https://github.com/jgarff/rpi_ws281x/issues/528

**Comment by caternuson** [comment]
This is an Arduino library. It has nothing to do with Raspbeery Pi and has no tie in with the rpi_ws281x repo.

**Comment by makermelissa** [comment]
@ubopod, there's already an issue open that you may want to watch: https://github.com/adafruit/Adafruit_Blinka/issues/747
