### ISSUE TITLE
Attinny85

### ISSUE THREAD

**Issue by alfredomova** [adafruit/Adafruit_NeoPixel#38]
I'm trying to control a strip of a single Neopixel with an Attiny85 @ 16Mhz (internal PLL, 4.3 V BOD) but it just doesn't work. the example "strandtest" just makes the led stuck in green, any help? i'm just connecting the data cable of the neopixel to the Pin 7 (PB2) in the Attiny, i also try putting a resistor in this but it doesn't  help.

                     ATTINY85
               ____________
               | RST      VCC | ---- 5v          (330ohms)                  grn----- | GND
               | PB3       PB2 | ---------------------ww------------------------------ | DI             NEOPIXEL
               | PB4       PB1 |                                                         5v----- | 5V
   grn----- | GRN      PB0 |
               ____________

#define PIN 2
// How many NeoPixels are attached to the Arduino?
#define NUMPIXELS      1

**Comment by tdicola** [comment]
Try posting in the forums at http://forums.adafruit.com/, there are more folks that might be able to help troubleshoot your setup.  Thanks!
