### ISSUE TITLE
simple example NEO_GRB won't work 

### ISSUE THREAD

**Issue by YufeiJ1ao** [adafruit/Adafruit_NeoPixel#390]
- Arduino board: arduino leonardo

- Arduino IDE version (found in Arduino -> About Arduino menu): 1.8.19 (Windows store 1.8.57.0)

- List the steps to reproduce the problem below 

When running Adafruit Neopixel simple example, the LED light stripe was flashing 
`Adafruit_NeoPixel pixels(NUMPIXELS, PIN, NEO_GRB + NEO_KHZ800);
`
![287382375785323383](https://github.com/adafruit/Adafruit_NeoPixel/assets/93790647/0556ea9c-2a40-42d9-b632-4feb2fb7544b)

When change NEO_GRB to NEO_GRBW the colour turns normal
`Adafruit_NeoPixel strip = Adafruit_NeoPixel(NUMPIXELS, PIN, NEO_GRBW + NEO_KHZ800);`
![111878991266611730](https://github.com/adafruit/Adafruit_NeoPixel/assets/93790647/e9c34a97-844d-4747-aed4-028d14e5b5d2)

Is it possible to start a pull request to make a change?

**Comment by hlcm0** [comment]
This is probably because your led strip type is RGBW, which need 4 bytes of data for each pixel. So you should use "GRBW" rather than "GRB". "GRB" is for ordinary RGB strips.

**Comment by caternuson** [comment]
Agree, sounds like you have RGBW NeoPixels with the color order being GRBW. Needing to change the code to match the NeoPixels being used is expected and is a necessary step.

> When change NEO_GRB to NEO_GRBW the colour turns normal

It all works as expected once the necessary code change has been made?

**Comment by caternuson** [comment]
Closing due to lack of response.
