### ISSUE TITLE
Incompatibility with digispark digiusb

### ISSUE THREAD

**Issue by Honos2014** [adafruit/Adafruit_NeoPixel#45]
Hi there,
Not sure if here is the good place to mention that...
NeoPixel with digispark runs perfectly but as soon as I include digiusb, just include the file, before or after including neopixel, I can no longer control the NeoPixel.
Thanks

**Comment by ladyada** [comment]
dunno, you'll have to ask digispark about it. we don't have one on hand to test with. could be you're running out of RAM
