### ISSUE TITLE
Computer says that master file is invalid

### ISSUE THREAD

**Issue by MaKenzieC** [adafruit/Adafruit_NeoPixel#78]
Here's the error message it keeps giving me: 

Arduino: 1.6.6 (Mac OS X), Board: "Arduino/Genuino Uno"

/Users/cgoldman/Documents/Arduino/cloud-lightning/cloudlightning_trial1.ino:31:31: fatal error: Adafruit_NeoPixel.h: No such file or directory
 #include <Adafruit_NeoPixel.h>
                               ^
compilation terminated.
exit status 1
Error compiling.
Invalid library found in /Users/cgoldman/Documents/Arduino/libraries/Adafruit_NeoPixel-master: /Users/cgoldman/Documents/Arduino/libraries/Adafruit_NeoPixel-master

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

If anyone could help me or at least point me in the direction of someone who could help, I would really appreciate it!!

**Comment by ruscoe** [comment]
Looks like you just need to rename that library directory from "Adafruit_NeoPixel-master" to "Adafruit_NeoPixel"

**Comment by MaKenzieC** [comment]
Thank you!
