### ISSUE TITLE
flashing strip with esp-12

### ISSUE THREAD

**Issue by i-n-g-o** [adafruit/Adafruit_NeoPixel#79]
Hi.

using current master i see flashes once and a while (quite often actually) using a neopixel-strip with esp-12.
I use pin-2 to drive the strip, power it directly from a LiPo and use a quite big (620uF) capacitor to stabilize the voltage.
I am using the strandtest example with the latest esp8266 version for Arduino (2.0.0-rc1)

**Comment by i-n-g-o** [comment]
ping

**Comment by PaintYourDragon** [comment]
Can't reproduce issue. Tested strandtest on ESP-12 (Adafruit HUZZAH) pin 2, Arduino IDE 1.6.5 against both stable (1.6.5) and staging (2.0.0-rc1) versions of esp8266, 5V USB or 3.7V LiPoly.

**Comment by xopr** [comment]
Are you using (hardware) Serial at the same time?
I've come across a similar issue when using NeoPixels, PN532 and Serial (for debugging).
It became stable after I added Serial.end() and Serial.begin( baudRate ) around the pixels.show() command.

**Comment by i-n-g-o** [comment]
finally i came around to continue with this.

for testing i use the example `strandtest`, which does not use Serial.

but throwing in a `Serial.end();`does not improve the situation.
even turning off interrupts with `cli();` does not solve this issue.
still i get occasional flashes on the strip.

i tested with 3.7V directly from a LiPo and with wall-plugged 5V

**Comment by i-n-g-o** [comment]
ah!
seems to have been a bad connection after all. ;)
testing for longer, but looks good.

thanks for the replies.

**Comment by i-n-g-o** [comment]
runs perfectly :)

**Comment by xopr** [comment]
Ah, nice!
The trouble I had was a weak power supply; actually, it ran from the FTDI adapter, so I'm glad it didn't break down on me. Disabling CPU load by disabling serial made te problem less apparent, so for other people running into these kind of problems: good and stable power supply is key (and good connection of course :) .

**Comment by i-n-g-o** [comment]
right.
my bad connection was at the data-pin to the strip which i connected using a breadboard.
after soldering the connection it worked.
