### ISSUE TITLE
typedef for neoPixelType appears wrong with respect to NEO_KHZ400

### ISSUE THREAD

**Issue by OliWright** [adafruit/Adafruit_NeoPixel#81]
The code defining the typedef for neoPixelType appears to be the wrong way round with respect to NEO_KHZ400 according to the comment.
The comment suggests that if NEO_KHZ400 is defined, then neoPixelType should be 16 bit, but if it's not, then 8 bit is sufficient.  But the code does the opposite...
```
// If 400 KHz support is enabled, the third parameter to the constructor
// requires a 16-bit value (in order to select 400 vs 800 KHz speed).
// If only 800 KHz is enabled (as is default on ATtiny), an 8-bit value
// is sufficient to encode pixel color order, saving some space.

#ifdef NEO_KHZ400
typedef uint8_t  neoPixelType;
#else
typedef uint16_t neoPixelType;
#endif
```

**Comment by PaintYourDragon** [comment]
Quite right, thanks for spotting. Fixed!
