### ISSUE TITLE
feature: add per pixel brightness capability

### ISSUE THREAD

**Issue by tablatronix** [adafruit/Adafruit_NeoPixel#87]
It would be nice to set per pixel brightness via `setPixelBrightness` or `setPixelColor(...,brightness)`

**Comment by damiangr** [comment]
I need this functionality too. In my project I have to store LED color and change only the state to on or off.

**Comment by tablatronix** [comment]
as a workaround, You can set maxbrightness to 255 then control offsets using your own function

```C++
void setColorwBrightness(uint16_t n, uint8_t r, uint8_t g, uint8_t b, uint16_t brightness){
  strip.setPixelColor(n, (brightness*r/255) , (brightness*g/255), (brightness*b/255));
}
```

But you will lose your rgb values, so you must keep track of them yourself if you need them.

**Comment by ladyada** [comment]
wont happen in this library as it would bloat RAM quite a bit! please feel free to fork :)
