### ISSUE TITLE
RGBWstrandtest fails to show up in IDE Examples menu

### ISSUE THREAD

**Issue by HamishB** [adafruit/Adafruit_NeoPixel#97]
Hi,

the RGBWstrandtest example does not show up in the Arduino IDE (Debian/stable's ver. 1.0.5) as the directory name does not match the .ino filename within it. Renaming RGBW_strandtest.ino to RGBWstrandtest.ino (or vice versa, renaming the directory to add an underscore) fixes it.

thanks,
Hamish

**Comment by ladyada** [comment]
ok
